### ISSUE TITLE
Move out of Beta

### ISSUE THREAD

**Issue by travier** [flathub/org.kde.amarok#5]
With the Amarok 3.0 release, this should be in a good enough shape to go out of Beta.

Testing and feedback welcomed.

**Comment by faveoled** [comment]
MPRIS doesn't seem to be working for me (I can't pause music using Gnome interface), Ubuntu 22.04

**Comment by travier** [comment]
Hum, Elisa has https://github.com/flathub/org.kde.elisa/blob/master/org.kde.elisa.json#L19 where Amarok has https://github.com/flathub/org.kde.amarok/blob/beta/org.kde.amarok.json#L30

**Comment by travier** [comment]
Giving this a try in https://github.com/flathub/org.kde.amarok/pull/9

**Comment by travier** [comment]
Ah, this looks like https://github.com/flathub/org.kde.amarok/pull/8 instead
